texture "1.png" _1
texture "2.png" _2
texture "3.png" _3
texture "4.png" _4
texture "5.png" _5
texture "6.png" _6
texture "7.png" _7
texture "8.png" _8
texture "9.png" _9
texture "10.png" _10
texture "11.png" _11
texture "12.png" _12
texture "13.png" _13
texture "14.png" _14
texture "15.png" _15
texture "16.png" _16



animation song
frame _1
sleep 300
frame _2
sleep 300
frame _3
sleep 300
frame _4
sleep 300
frame _5
sleep 300
frame _6
sleep 300
frame _7
sleep 300
frame _8
sleep 300
frame _9
sleep 300
frame _10
sleep 300
frame _11
sleep 300
frame _12
sleep 300
frame _13
sleep 300
frame _14
sleep 300
frame _15
sleep 300
frame _16
sleep 300
loop -1
goto song
end

