#ifndef PX_SOUNDLAB_H
#define PX_SOUNDLAB_H

#include "PX_Script_VM.h"

typedef enum
{
	PX_SOUNDLAB_STFT_WINDOW_SIZE_256,
	PX_SOUNDLAB_STFT_WINDOW_SIZE_512,
	PX_SOUNDLAB_STFT_WINDOW_SIZE_1024,
	PX_SOUNDLAB_STFT_WINDOW_SIZE_2048,
	PX_SOUNDLAB_STFT_WINDOW_SIZE_4096,
	PX_SOUNDLAB_STFT_WINDOW_SIZE_8192,
}PX_SOUNDLAB_STFT_WINDOW_SIZE;

typedef struct
{
	px_memorypool *mp;
	PX_SoundData SoundData;
	PX_SOUNDLAB_STFT_WINDOW_SIZE STFT_WINDOW;
}PX_SoundLab;

#endif
