////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//  PX_Ed25519
//
//  PainterEngine Ed25519 Digital Signature Algorithm Implementation
//
//  Ed25519 is a high-speed, high-security elliptic curve digital signature algorithm based on
//  Twisted Edwards curves. It operates on the curve -x^2 + y^2 = 1 + d*x^2*y^2 over GF(2^255-19),
//  providing ~128-bit security level with 32-byte keys and 64-byte signatures.
//
//  This implementation is adapted from the portable C implementation by Orson Peters, which is
//  based on the SUPERCOP "ref10" reference implementation by Daniel J. Bernstein, Niels Duif,
//  Tanja Lange, Peter Schwabe, and Bo-Yin Yang.
//
//  Acknowledgments:
//    - Original portable C implementation: Orson Peters <orsonpeters@gmail.com>
//      https://github.com/orlp/ed25519  (zlib license)
//    - SUPERCOP ref10: Daniel J. Bernstein et al.
//      http://ed25519.cr.yp.to/
//    - SHA-512 implementation from WjCryptLib by WaterJuice (Public Domain)
//
//  Original license (zlib):
//    Copyright (c) 2015 Orson Peters <orsonpeters@gmail.com>
//    This software is provided 'as-is', without any express or implied warranty.
//    Permission is granted to anyone to use this software for any purpose, including commercial
//    applications, and to alter it and redistribute it freely, subject to the following restrictions:
//    1. The origin of this software must not be misrepresented.
//    2. Altered source versions must be plainly marked as such.
//    3. This notice may not be removed or altered from any source distribution.
//
//  This is an altered version adapted for PainterEngine's cross-platform type system and naming
//  conventions. All standard C types have been replaced with PainterEngine portable types
//  (px_byte, px_int32, px_uint64, etc.) and SHA-512 uses PainterEngine's built-in implementation.
//
//  Features:
//    - Keypair generation from 32-byte seed
//    - Deterministic message signing (RFC 8032 compatible)
//    - Signature verification
//    - Keypair scalar addition (for key derivation / hierarchical key schemes)
//    - Elliptic Curve Diffie-Hellman key exchange
//
//  Buffer sizes:
//    Seed:           32 bytes (PX_ED25519_SEED_SIZE)
//    Public key:     32 bytes (PX_ED25519_PUBLIC_KEY_SIZE)
//    Private key:    64 bytes (PX_ED25519_PRIVATE_KEY_SIZE)
//    Signature:      64 bytes (PX_ED25519_SIGNATURE_SIZE)
//    Scalar:         32 bytes (PX_ED25519_SCALAR_SIZE)
//    Shared secret:  32 bytes (PX_ED25519_SHARED_SECRET_SIZE)
//
//  API:
//
//    PX_Ed25519_CreateKeypair(public_key, private_key, seed)
//        Creates a new Ed25519 key pair from the given 32-byte seed.
//        The seed should be generated by a cryptographically secure random number generator.
//        - public_key:  [out] writable 32-byte buffer for the public key
//        - private_key: [out] writable 64-byte buffer for the private key
//        - seed:        [in]  32-byte random seed
//
//    PX_Ed25519_Sign(signature, message, message_len, public_key, private_key)
//        Creates a deterministic Ed25519 signature over the given message.
//        - signature:   [out] writable 64-byte buffer for the signature
//        - message:     [in]  message bytes to sign
//        - message_len: [in]  length of the message in bytes
//        - public_key:  [in]  32-byte public key
//        - private_key: [in]  64-byte private key
//
//    PX_Ed25519_Verify(signature, message, message_len, public_key)
//        Verifies an Ed25519 signature over the given message.
//        Returns 1 if the signature is valid, 0 otherwise.
//        - signature:   [in]  64-byte signature to verify
//        - message:     [in]  message bytes
//        - message_len: [in]  length of the message in bytes
//        - public_key:  [in]  32-byte public key of the signer
//
//    PX_Ed25519_AddScalar(public_key, private_key, scalar)
//        Adds a 32-byte scalar to the given key pair, producing a new derived key pair.
//        Either public_key or private_key may be PX_NULL if you only want to derive one.
//        This is useful for hierarchical key derivation or third-party key randomization.
//        Warning: the highest bit of scalar[31] is ignored.
//        - public_key:  [in/out] 32-byte public key (or PX_NULL to skip)
//        - private_key: [in/out] 64-byte private key (or PX_NULL to skip)
//        - scalar:      [in]     32-byte scalar value to add
//
//    PX_Ed25519_KeyExchange(shared_secret, public_key, private_key)
//        Performs an Elliptic Curve Diffie-Hellman key exchange.
//        Both parties compute the same shared secret from their own private key and the
//        other party's public key. It is recommended to hash the shared secret before use.
//        - shared_secret: [out] writable 32-byte buffer for the shared secret
//        - public_key:    [in]  32-byte public key of the other party
//        - private_key:   [in]  64-byte private key of this party
//
//  Example:
//
//    px_byte seed[32], public_key[32], private_key[64], signature[64];
//    const px_byte message[] = "Hello PainterEngine";
//
//    // Generate seed with your platform's CSPRNG, then:
//    PX_Ed25519_CreateKeypair(public_key, private_key, seed);
//    PX_Ed25519_Sign(signature, message, 19, public_key, private_key);
//
//    if (PX_Ed25519_Verify(signature, message, 19, public_key)) {
//        // signature is valid
//    }
//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PX_ED25519_H
#define PX_ED25519_H

#include "PX_Typedef.h"
#include "PX_Sha.h"

#define PX_ED25519_SEED_SIZE        32
#define PX_ED25519_PUBLIC_KEY_SIZE  32
#define PX_ED25519_PRIVATE_KEY_SIZE 64
#define PX_ED25519_SIGNATURE_SIZE   64
#define PX_ED25519_SCALAR_SIZE      32
#define PX_ED25519_SHARED_SECRET_SIZE 32

px_void PX_Ed25519_CreateKeypair(px_byte public_key[32], px_byte private_key[64], const px_byte seed[32]);
px_void PX_Ed25519_Sign(px_byte signature[64], const px_byte *message, px_int message_len, const px_byte public_key[32], const px_byte private_key[64]);
px_int  PX_Ed25519_Verify(const px_byte signature[64], const px_byte *message, px_int message_len, const px_byte public_key[32]);
px_void PX_Ed25519_AddScalar(px_byte *public_key, px_byte *private_key, const px_byte scalar[32]);
px_void PX_Ed25519_KeyExchange(px_byte shared_secret[32], const px_byte public_key[32], const px_byte private_key[64]);

#endif
