#name "stdlib.h"
#runtime stack 1024
host int loadimage(string url,string key);
host int loadsound(string url,string key);
host void message(string message);
host void print(string s);
host void lastprint(string s);
host float getplayerx();
host float getplayery();
host void createplayer(float x, float y,float size);
host void setplayerpos(float x, float y);
host float sin(float x);
host float cos(float x);
host float sqrt(float x);
host float atan(float y,float x);
host int rand();
host void setlayer(int layer);
host void clearmap(float a,float r,float g,float b);
host void pen(float x,float y);
host void lineto(float x,float y,float linewidth,float a,float r,float g,float b);
host void drawline(float x0,float y0,float x1,float y1,float linewidth,float a,float r,float g,float b);
host void drawsolidcircle(float x,float y,float radius,float a,float r,float g,float b);
host void drawcircle(float x,float y,float radius,float linewidth,float a,float r,float g,float b);
host void drawrect(float x,float y,float w,float h,float a,float r,float g,float b);
host void drawtext(float x,float y,float a,float r,float g,float b,string text);
host void drawimage(float x,float y,float rotation,float scale,string name);
host void drawbackgroundimage(float x,float y,string name);
host void createtext(float x,float y,float a,float r,float g,float b,string text,int alive);
host void createimage(float x,float y,string name,int alive);
host void createfood(float x,float y,float a,float r,float g,float b,float size,string id); 
host void createtrigger(float x,float y,float width,float height,string id); 
host void setspeed(float s);
host void playsound(string key);
host void sleep(int ms);
host void gamestart();
host void gamepause();
host void defeat();
host void victory();
host void runnextgame(string url);
host int wait(int ms);