#ifndef SOD_TEXT_H
#define SOD_TEXT_H

#define SOD_PATH_SND_EXPLODE01 "../Resources/explosion01.wav"
#define SOD_PATH_SND_EXPLODE02 "../Resources/explosion02.wav"
#define SOD_PATH_SND_EXPLODE03 "../Resources/explosion03.wav"

#define SOD_PATH_ANIMATION_USERDEF "../Resources/cxk/cxk.2dx"
#define SOD_PATH_ANIMATION_AATOM "../Resources/aatom/aatom.2dx"
#define SOD_PATH_ANIMATION_ALIEN "../Resources/alien/alien.2dx"

#define SOD_PATH_HUAJI "../Resources/cxk/ball.traw"
#define SOD_PATH_SHIELD "../Resources/shield.traw"
#define SOD_PATH_PSTAR "../Resources/star/pstar.traw"
#define SOD_PATH_ANIMATION_STAR "../Resources/star/star.2dx"
#define SOD_PATH_ANIMATION_GHOST "../Resources/ghost/ghost.2dx"
#define SOD_PATH_ALIEN_FIRE "../Resources/alien_Fire.wav"
#define SOD_PATH_ABOUT "../Resources/about.traw"
#define SOD_PATH_BGM "../Resources/Tech World Unite.wav"
#define SOD_PATH_GAMEOVER "../Resources/gameover.traw"
#define SOD_PATH_EXPLODE_PARTICAL "../Resources/explode_partical.traw"
#define SOD_PATH_STONE1 "../Resources/stone01.traw"
#define SOD_PATH_STONE2 "../Resources/stone02.traw"
#define SOD_PATH_STONE3 "../Resources/stone03.traw"
#define SOD_PATH_SHIP_FIRE_SHIP_ATOM "../Resources/ship_atom.traw"
#define SOD_PATH_SHIP_FIRE "../Resources/ship_fire.wav"
#define SOD_PATH_PARTICAL_FIRE_ASH "../Resources/fire_ash.traw"
#define SOD_PATH_PARTICAL_FIRE_LARGE "../Resources/p_fire_l.traw"
#define SOD_PATH_CURSOR "../Resources/cursor.traw"
#define SOD_PATH_SHIP "../Resources/ship.traw"
#define SOD_PATH_FONTMODULE "../Resources/sod.pxf"
#define SOD_PATH_STARTUP_BACKGROUND "../Resources/startup.traw"
#define SOD_PATH_BTN_ALERT "../Resources/btn_alert.wav"
#define SOD_PATH_BTN_CLICK "../Resources/btn_click.wav"
#define SOD_PATH_STARAPPLY "../Resources/starapply.wav"

#define SOD_KEY_TEX_HUAJI "tex_huajibt"
#define SOD_KEY_ANIMATION_USERDEF "ani_userdef"
#define SOD_KEY_ANIMATION_STAR "ani_star"
#define SOD_KEY_ANIMATION_ALIEN "ani_alien"
#define SOD_KEY_ANIMATION_AATOM "ani_aatom"
#define SOD_KEY_ANIMATION_GHOST "ani_ghost"
#define SOD_KEY_TEX_ABOUT	  "tex_about"
#define SOD_KEY_TEXT_GAMEOVER "txt_gameover"
#define SOD_KEY_SND_ALIEN_FIRE "snd_alienfire"
#define SOD_KEY_SND_EXPLODE01 "snd_exps01"
#define SOD_KEY_SND_EXPLODE02 "snd_exps02"
#define SOD_KEY_SND_EXPLODE03 "snd_exps03"
#define SOD_KEY_SND_BGM		  "bgm"
#define SOD_KEY_SND_STARAPPLY "snd_starapply"

#define SOD_KEY_TEX_SHIELD "tex_shield"
#define SOD_KEY_TEX_STAR "tex_star"
#define SOD_KEY_TEX_EXPLODE_PARTICAL "tex_explode_partical"
#define SOD_KEY_TEX_STONE1 "tex_stone1"
#define SOD_KEY_TEX_STONE2 "tex_stone2"
#define SOD_KEY_TEX_STONE3 "tex_stone3"
#define SOD_KEY_TEX_SHIP_ATOM "tex_ship_atom"
#define SOD_KEY_TEX_SHIP "tex_ship"
#define SOD_KEY_BTN_ALERT "btn_alert"
#define SOD_KEY_BTN_CLICK "btn_click"
#define SOD_KEY_SOUND_SHIP_FIRE "snd_shipfire"
#define SOD_KEY_PARTICAL_FIRE_LARGE "tex_fire"
#define SOD_KEY_PARTICAL_FIRE_ASH "fire_ash"

#define SOD_ANIMATION_KEY_ALIEN_VERYANGRY "ALIEN_VERYANGRY"
#define SOD_ANIMATION_KEY_ALIEN_ANGRY "ALIEN_ANGRY"
#define SOD_ANIMATION_KEY_ALIEN_NORMAL "ALIEN_NORMAL"
#define SOD_ANIMATION_KEY_AATOM_NORMAL "MAIN"
#define SOD_ANIMATION_KEY_STAR_NORMAL "MAIN"
#define SOD_ANIMATION_KEY_USERDEF_NORMAL "MAIN"

#define SOD_ANIMATION_KEY_GHOST_ANGRY "GHOST_ANGRY"
#define SOD_ANIMATION_KEY_GHOST_NORMAL "GHOST_NORMAL"

#define SOD_TEXT_OK "确定"
#define SOD_TEXT_YES "是"
#define SOD_TEXT_NO  "否"
#define SOD_TEXT_START_GAME L"开始游戏"
#define SOD_TEXT_ABOUT L"关于"
#define SOD_TEXT_EXIT_GAME L"退出游戏"
#define SOD_TEXT_SCORE L"分数:"
#define SOD_TEXT_ALIVE_TIME "生存时间:%d.%ds"
#define SOD_TEXT_GAMEOVER L"Game Over"
#define SOD_TEXT_HEALTH "生命恢复"
#define SOD_TEXT_ADD_ATOM "子弹补充"
#define SOD_TEXT_FORCE_UP "动力提升"
#define SOD_TEXT_WEAPON_UP "攻击加速"
#define SOD_TEXT_SHIELD "护盾"
#define SOD_TEXT_ADD_SCORE "+100分数"
#endif