texture "jump 0.png" jump_0
texture "jump up.png" jump_up
texture "jump down.png" jump_down
texture "run 1.png" run_1
texture "run 2.png" run_2
texture "run 3.png" run_3
texture "run 4.png" run_4
texture "run 5.png" run_5
texture "run 6.png" run_6
texture "walk 1.png" walk_1
texture "walk 2.png" walk_2
texture "walk 3.png" walk_3
texture "walk 4.png" walk_4
texture "walk 5.png" walk_5
texture "walk 6.png" walk_6

animation jump_begin
frame jump_0
sleep 50
frame jump_up
end

animation jump_down
frame jump_down
end

animation run
loop -1
tag run_begin
frame run_1
sleep 60
frame run_2
sleep 60
frame run_3
sleep 60
frame run_4
sleep 60
frame run_5
sleep 60
frame run_6
sleep 60
goto run_begin
end

animation walk
loop -1
tag walk_begin
frame walk_1
sleep 100
frame walk_2
sleep 100
frame walk_3
sleep 100
frame walk_4
sleep 100
frame walk_5
sleep 100
frame walk_6
sleep 100
goto walk_begin
end