texture "run.png" run
texture "walk.png" walk
texture "jump.png" jump
texture "idol.png" idol

animation run
frame run
clipx 0
clipy 0
clipw 233
cliph 257

loop 17
clipi 0
tag $run_begin
sleep 60
clipinc 1
goto $run_begin
loop -1
goto run
end

animation walk
frame walk
clipx 0
clipy 0
clipw 178
cliph 249

loop 23
clipi 0
tag $walk_begin
sleep 60
clipinc 1
goto $walk_begin
loop -1
goto walk
end

animation jump
frame jump
clipx 0
clipy 0
clipw 170
cliph 278
loop 48
clipi 0
tag $jump_begin
sleep 60
clipinc 1
goto $jump_begin
loop -1
goto jump
end

animation idol
frame idol
clipx 0
clipy 0
clipw 153
cliph 245
loop 39
clipi 0
tag $idol_begin
sleep 60
clipinc 1
goto $idol_begin
loop -1
goto idol
end